### ISSUE TITLE
Neglected Oranges is showing different counts than intermittent failures view in treeherder

### ISSUE THREAD

**Issue by jmaher** [klahnakoski/InactiveOranges#4]
The code sheriffs brought this to my attention this morning.  I looked into this a bit.

Looking at bug 1471553, I see 44 failures in IFV:
https://treeherder.mozilla.org/intermittent-failures.html#/bugdetails?startday=2018-08-14&endday=2018-08-21&tree=trunk&bug=1471553

and 19 in neglected oranges (here is the query for it):
https://activedata.allizom.org/tools/query.html#query_id=5GZa+vA3

I hacked on the query to see the raw data by removing the grouping:
https://activedata.allizom.org/tools/query.html#query_id=0XVq8aYP

and this gives me the same 44 data points as we see in IFV.

@klahnakoski - I assume this is something we can modify in the query, or is this something wrong with the ES database?

**Comment by klahnakoski** [comment]
Probably just the query.

Counting the "bugs.bug_id" rather than the "bug" gives a better number:

https://activedata.allizom.org/tools/query.html#query_id=4gDAL8ck

**Comment by klahnakoski** [comment]
I pushed a fix  https://github.com/klahnakoski/NeglectedOranges/commit/d8520f25f26db1fb5c2a0007d8d63ab4763af605

It should be visible in under 24 hours

**Comment by klahnakoski** [comment]
The last change was not good.  https://github.com/klahnakoski/NeglectedOranges/issues/5 had another fix that still gives a good number here.
