### ISSUE TITLE
NeglectedOranges miscalculates data

### ISSUE THREAD

**Issue by jmaher** [klahnakoski/InactiveOranges#5]
IFV shows 22 failures:
https://treeherder.mozilla.org/intermittent-failures.html#/bugdetails?startday=2018-08-16&endday=2018-08-23&tree=all&bug=1473207

Activedata shows 22 failures:
https://activedata.allizom.org/tools/query.html#query_id=8AmvuBEY

But neglected oranges shows 40 failures:
https://activedata.allizom.org/tools/query.html#query_id=mRjoOdmR

@klahnakoski is there a way you can take another look at this query?

**Comment by klahnakoski** [comment]
Ok, this looks like it will be more complicated:  Treeherder can markup one task with multiple bugs, so the counting gets complicated.  The next step is to list all tasks from OrangeFactor and ActiveData; adding a column for each bug the task is annotated with.  This will allow an easier cross-compare, and point us to a specific task that that should (or should not) be in either count.

Thinking a bit more:  It looks like COUNT(bugs.bug_id) is counting the "other bug" also.  Let me try a quick fix....

**Comment by klahnakoski** [comment]
Counting the number of records, not the number of bugs, is more accurate:  https://activedata.allizom.org/tools/query.html#query_id=rzKvoJF6

I pushed a change that we can see tomorrow: https://github.com/klahnakoski/NeglectedOranges/commit/c6326c7ffd19070ebd4662355fe6d5a851449aa0

This may bring us back to the last bug, https://github.com/klahnakoski/NeglectedOranges/issues/4 , which i will look at now
